// Full logical backup of the ilmsoft Supabase database (free tier has no backups).
// Read-only. Writes backups/<timestamp>/{schema.sql, data/<schema.table>.json, manifest.json}.
// Restore: node scripts/db_restore.mjs backups/<timestamp>   (see that file for the exact steps)
//
// Usage: node scripts/db_dump.mjs
import fs from 'node:fs';
import path from 'node:path';
import pg from 'pg';

const env = Object.fromEntries(
  fs.readFileSync('.env.local', 'utf8').split('\n').filter(l => l.includes('='))
    .map(l => { const i = l.indexOf('='); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]; })
);
const client = new pg.Client({
  host: env.SUPABASE_DB_HOST, port: +env.SUPABASE_DB_PORT, database: env.SUPABASE_DB_NAME,
  user: env.SUPABASE_DB_USER, password: env.SUPABASE_DB_PASSWORD, ssl: { rejectUnauthorized: false },
});
await client.connect();
await client.query('SET default_transaction_read_only = on');
await client.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY'); // one consistent snapshot for every table

const stamp = new Date().toISOString().replace(/[:.]/g, '-');
const dir = path.join('backups', stamp);
fs.mkdirSync(path.join(dir, 'data'), { recursive: true });
const q = async (sql, p = []) => (await client.query(sql, p)).rows;

// ---------- schema.sql (best-effort DDL; pg_dump is not installed on this machine)
const ddl = [`-- ilmsoft schema snapshot ${stamp}\n-- Generated by scripts/db_dump.mjs. Best-effort DDL for public schema.\n`];
const tables = await q(`SELECT c.relname AS t FROM pg_class c WHERE c.relnamespace='public'::regnamespace AND c.relkind='r' ORDER BY 1`);
for (const { t } of tables) {
  const cols = await q(`SELECT a.attname, pg_catalog.format_type(a.atttypid, a.atttypmod) typ, a.attnotnull nn, pg_get_expr(d.adbin, d.adrelid) def
     FROM pg_attribute a LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum
     WHERE a.attrelid=('public.'||quote_ident($1))::regclass AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum`, [t]);
  ddl.push(`CREATE TABLE IF NOT EXISTS public.${t} (\n` + cols.map(c => `  ${c.attname} ${c.typ}${c.nn ? ' NOT NULL' : ''}${c.def ? ' DEFAULT ' + c.def : ''}`).join(',\n') + `\n);`);
  const rls = await q(`SELECT relrowsecurity r FROM pg_class WHERE oid=('public.'||quote_ident($1))::regclass`, [t]);
  ddl.push(`ALTER TABLE public.${t} ${rls[0].r ? 'ENABLE' : 'DISABLE'} ROW LEVEL SECURITY;`);
}
ddl.push('\n-- constraints (primary keys and uniques first, then foreign keys, then checks)');
for (const ct of ['p', 'u', 'c', 'f']) {
  const cons = await q(`SELECT conrelid::regclass::text tbl, conname, pg_get_constraintdef(oid) def FROM pg_constraint WHERE connamespace='public'::regnamespace AND contype=$1 ORDER BY 1,2`, [ct]);
  for (const c of cons) ddl.push(`ALTER TABLE ${c.tbl} ADD CONSTRAINT ${c.conname} ${c.def};`);
}
ddl.push('\n-- indexes (non-constraint)');
const idx = await q(`SELECT indexdef FROM pg_indexes i WHERE schemaname='public' AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conname=i.indexname) ORDER BY tablename, indexname`);
for (const i of idx) ddl.push(i.indexdef + ';');
ddl.push('\n-- views');
for (const v of await q(`SELECT table_name, view_definition FROM information_schema.views WHERE table_schema='public'`)) ddl.push(`CREATE OR REPLACE VIEW public.${v.table_name} AS ${v.view_definition}`);
ddl.push('\n-- functions');
for (const f of await q(`SELECT pg_get_functiondef(p.oid) def FROM pg_proc p WHERE p.pronamespace='public'::regnamespace ORDER BY p.proname`)) ddl.push(f.def + ';');
ddl.push('\n-- triggers');
for (const t of await q(`SELECT pg_get_triggerdef(t.oid) def FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid WHERE NOT t.tgisinternal AND c.relnamespace IN ('public'::regnamespace,'auth'::regnamespace) ORDER BY c.relname, t.tgname`)) ddl.push(t.def + ';');
ddl.push('\n-- policies');
const pols = await q(`SELECT c.relname tbl, p.polname, p.polcmd, p.polpermissive perm, ARRAY(SELECT rolname::text FROM pg_roles WHERE oid=ANY(p.polroles)) roles, pg_get_expr(p.polqual,p.polrelid) q, pg_get_expr(p.polwithcheck,p.polrelid) w FROM pg_policy p JOIN pg_class c ON c.oid=p.polrelid WHERE c.relnamespace='public'::regnamespace ORDER BY 1,2`);
for (const p of pols) {
  const cmd = { r: 'SELECT', a: 'INSERT', w: 'UPDATE', d: 'DELETE', '*': 'ALL' }[p.polcmd];
  const roles = (Array.isArray(p.roles) ? p.roles : String(p.roles).replace(/[{}]/g, '').split(',').filter(Boolean));
  ddl.push(`CREATE POLICY "${p.polname}" ON public.${p.tbl} AS ${p.perm ? 'PERMISSIVE' : 'RESTRICTIVE'} FOR ${cmd}${roles.length ? ' TO ' + roles.join(', ') : ''}${p.q ? `\n  USING (${p.q})` : ''}${p.w ? `\n  WITH CHECK (${p.w})` : ''};`);
}
ddl.push('\n-- grants (anon / authenticated / service_role)');
const grants = await q(`SELECT table_name, grantee, string_agg(privilege_type, ', ' ORDER BY privilege_type) privs FROM information_schema.role_table_grants WHERE table_schema='public' AND grantee IN ('anon','authenticated','service_role') GROUP BY 1,2 ORDER BY 1,2`);
for (const g of grants) ddl.push(`GRANT ${g.privs} ON public.${g.table_name} TO ${g.grantee};`);
ddl.push('\n-- function execute grants');
const fg = await q(`SELECT p.proname||'('||pg_get_function_identity_arguments(p.oid)||')' sig, (SELECT string_agg(r, ', ') FROM unnest(ARRAY['anon','authenticated','service_role']) r WHERE has_function_privilege(r::text, p.oid, 'EXECUTE')) roles FROM pg_proc p WHERE p.pronamespace='public'::regnamespace ORDER BY 1`);
for (const f of fg) if (f.roles) ddl.push(`GRANT EXECUTE ON FUNCTION public.${f.sig} TO ${f.roles};`);
ddl.push('\n-- storage buckets');
for (const b of await q(`SELECT id, name, public, file_size_limit, allowed_mime_types FROM storage.buckets`)) ddl.push(`-- bucket ${b.id}: public=${b.public} size_limit=${b.file_size_limit} mime=${JSON.stringify(b.allowed_mime_types)}`);
for (const p of await q(`SELECT p.polname, p.polcmd, pg_get_expr(p.polqual,p.polrelid) q, pg_get_expr(p.polwithcheck,p.polrelid) w FROM pg_policy p WHERE p.polrelid='storage.objects'::regclass`)) ddl.push(`-- storage.objects policy "${p.polname}" cmd=${p.polcmd} USING(${p.q}) CHECK(${p.w})`);
fs.writeFileSync(path.join(dir, 'schema.sql'), ddl.join('\n') + '\n');

// ---------- data: every public table + auth.users/identities, JSON rows, in FK-safe restore order
const fks = await q(`SELECT conrelid::regclass::text child, confrelid::regclass::text parent FROM pg_constraint WHERE contype='f' AND connamespace='public'::regnamespace AND conrelid<>confrelid`);
const deps = {}; for (const { t } of tables) deps[t] = new Set();
for (const f of fks) { const c = f.child.replace(/^public\./, ''), p = f.parent.replace(/^public\./, ''); if (deps[c] && deps[p]) deps[c].add(p); }
const order = []; const seen = new Set();
const visit = (t, stack = new Set()) => { if (seen.has(t)) return; if (stack.has(t)) return; stack.add(t); for (const d of deps[t]) visit(d, stack); seen.add(t); order.push(t); };
for (const { t } of tables) visit(t);

const manifest = { stamp, restore_order: ['auth.users', 'auth.identities', ...order.map(t => 'public.' + t)], counts: {}, note: 'Row counts are from one REPEATABLE READ snapshot.' };
const dumpTable = async (fq) => {
  const rows = await q(`SELECT row_to_json(t) r FROM ${fq} t`);
  fs.writeFileSync(path.join(dir, 'data', `${fq}.json`), JSON.stringify(rows.map(x => x.r)));
  manifest.counts[fq] = rows.length;
};
await dumpTable('auth.users');
await dumpTable('auth.identities');
for (const t of order) await dumpTable('public.' + t);
await client.query('COMMIT');
fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
await client.end();
console.log(`backup written to ${dir}`);
console.log(JSON.stringify(manifest.counts));
